// web/frontend/src/pages/Backup.jsx

import { useState, useEffect } from "react";

export default function BackupPage() {
  const [backups, setBackups] = useState([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [exporting, setExporting] = useState(null);

  const load = () => {
    fetch("/api/backup", { credentials: "include" })
      .then(r => r.json())
      .then(d => { setBackups(d.data || []); setLoading(false); })
      .catch(() => setLoading(false));
  };
  useEffect(() => { load(); }, []);

  const createBackup = async () => {
    setCreating(true);
    try {
      await fetch("/api/backup", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ action: "create" })
      });
      load();
    } catch {}
    setCreating(false);
  };

  const handleExport = async (type) => {
    setExporting(type);
    try {
      const r = await fetch("/api/backup", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ action: "export", type })
      });
      const blob = await r.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const ext = type === "analytics" ? "csv" : "json";
      a.download = `lintasan-${type}-${new Date().toISOString().slice(0, 10)}.${ext}`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {}
    setExporting(null);
  };

  const handleRestore = async (filename) => {
    if (!confirm(`Restore from backup "${filename}"? This will overwrite current configuration.`)) return;
    if (!confirm("Are you absolutely sure? This action cannot be undone.")) return;
    await fetch("/api/backup", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ action: "restore", filename })
    });
    load();
  };

  const handleDelete = async (filename) => {
    if (!confirm(`Delete backup "${filename}"?`)) return;
    await fetch("/api/backup", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ action: "delete", filename })
    });
    load();
  };

  const formatSize = (bytes) => {
    if (!bytes) return "—";
    if (bytes >= 1048576) return (bytes / 1048576).toFixed(1) + " MB";
    if (bytes >= 1024) return (bytes / 1024).toFixed(1) + " KB";
    return bytes + " B";
  };

  const formatDate = (d) => {
    if (!d) return "—";
    return new Date(d).toLocaleString();
  };

  if (loading) return <LoadingSkeleton />;

  return (
    <div className="fade-in">
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px" }}>
        <div>
          <h1 style={{ fontSize: "18px", fontWeight: 600, color: "var(--fg-0)", marginBottom: "4px" }}>Backup & Export</h1>
          <p style={{ fontSize: "13px", color: "var(--fg-3)" }}>Create backups and export configuration data</p>
        </div>
        <button onClick={createBackup} disabled={creating} style={btnPrimary}>
          {creating ? <><IconSpinner /> Creating...</> : <><IconPlus /> Create Backup</>}
        </button>
      </div>

      {/* Export Cards */}
      <div className="responsive-grid" style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px", marginBottom: "24px" }}>
        <div style={card}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
            <div style={{ ...iconBadge, background: "var(--primary-light)" }}><IconConfig color="var(--primary)" /></div>
            <div>
              <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--fg-0)" }}>Config JSON</p>
              <p style={{ fontSize: "11px", color: "var(--fg-3)" }}>Export all configuration</p>
            </div>
          </div>
          <button onClick={() => handleExport("config")} disabled={exporting === "config"} style={{ ...btnPrimary, width: "100%", justifyContent: "center" }}>
            {exporting === "config" ? "Exporting..." : "Export Config"}
          </button>
        </div>

        <div style={card}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
            <div style={{ ...iconBadge, background: "var(--success-light)" }}><IconChart color="var(--success)" /></div>
            <div>
              <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--fg-0)" }}>Analytics CSV</p>
              <p style={{ fontSize: "11px", color: "var(--fg-3)" }}>Export usage analytics</p>
            </div>
          </div>
          <button onClick={() => handleExport("analytics")} disabled={exporting === "analytics"} style={{ ...btnPrimary, width: "100%", justifyContent: "center", background: "var(--success)" }}>
            {exporting === "analytics" ? "Exporting..." : "Export Analytics"}
          </button>
        </div>

        <div style={card}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
            <div style={{ ...iconBadge, background: "var(--warning-light)" }}><IconArchive color="var(--warning)" /></div>
            <div>
              <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--fg-0)" }}>Full Export</p>
              <p style={{ fontSize: "11px", color: "var(--fg-3)" }}>Config + analytics + logs</p>
            </div>
          </div>
          <button onClick={() => handleExport("full")} disabled={exporting === "full"} style={{ ...btnPrimary, width: "100%", justifyContent: "center", background: "var(--warning)" }}>
            {exporting === "full" ? "Exporting..." : "Full Export"}
          </button>
        </div>
      </div>

      {/* Backups Table */}
      <h2 style={sectionTitle}>Saved Backups</h2>
      <div style={{ ...card, padding: 0, overflow: "hidden" }}>
        {backups.length === 0 ? (
          <EmptyState />
        ) : (
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13px" }} className="responsive-table">
            <thead>
              <tr style={{ background: "var(--bg-body)" }}>
                {["Filename", "Size", "Created", "Actions"].map(h => <th key={h} style={th}>{h}</th>)}
              </tr>
            </thead>
            <tbody>
              {backups.map((b, i) => (
                <tr key={i} style={row}>
                  <td style={td}>
                    <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                      <div style={{ width: "28px", height: "28px", borderRadius: "6px", background: "var(--primary-light)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <IconArchive color="var(--primary)" size={12} />
                      </div>
                      <span style={{ fontWeight: 500, color: "var(--fg-0)", fontFamily: "var(--mono)", fontSize: "12px" }}>{b.filename || b.name}</span>
                    </div>
                  </td>
                  <td style={td}><code style={mono}>{formatSize(b.size)}</code></td>
                  <td style={td}><span style={{ fontSize: "12px", color: "var(--fg-2)" }}>{formatDate(b.created_at || b.date)}</span></td>
                  <td style={{ ...td, textAlign: "right" }}>
                    <div style={{ display: "flex", gap: "6px", justifyContent: "flex-end" }}>
                      <button onClick={() => handleRestore(b.filename || b.name)} style={btnRestore}>
                        <IconRestore size={12} /> Restore
                      </button>
                      <button onClick={() => handleDelete(b.filename || b.name)} style={btnDangerSmall}><IconTrash size={14} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

/* Icons */
function IconPlus() { return <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>; }
function IconX() { return <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>; }
function IconTrash({ size = 14 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>; }
function IconConfig({ color = "currentColor" }) { return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>; }
function IconChart({ color = "currentColor" }) { return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>; }
function IconArchive({ color = "currentColor", size = 16 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round"><polyline points="21 8 21 21 3 21 3 8"/><rect x="1" y="3" width="22" height="5"/><line x1="10" y1="12" x2="14" y2="12"/></svg>; }
function IconRestore({ size = 14 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10"/></svg>; }
function IconSpinner() { return <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" style={{ animation: "spin 1s linear infinite" }}><line x1="12" y1="2" x2="12" y2="6"/><line x1="12" y1="18" x2="12" y2="22"/><line x1="4.93" y1="4.93" x2="7.76" y2="7.76"/><line x1="16.24" y1="16.24" x2="19.07" y2="19.07"/><line x1="2" y1="12" x2="6" y2="12"/><line x1="18" y1="12" x2="22" y2="12"/><line x1="4.93" y1="19.07" x2="7.76" y2="16.24"/><line x1="16.24" y1="7.76" x2="19.07" y2="4.93"/></svg>; }

function EmptyState() {
  return (
    <div style={{ padding: "48px", textAlign: "center" }}>
      <div style={{ width: "56px", height: "56px", borderRadius: "12px", background: "var(--bg-body)", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 16px" }}>
        <IconArchive color="var(--fg-3)" />
      </div>
      <p style={{ fontSize: "14px", fontWeight: 500, color: "var(--fg-1)", marginBottom: "4px" }}>No backups yet</p>
      <p style={{ fontSize: "13px", color: "var(--fg-3)" }}>Create a backup to save your current configuration</p>
    </div>
  );
}

function LoadingSkeleton() {
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "24px" }}>
        <div><div className="skeleton" style={{ width: "140px", height: "20px", borderRadius: "6px", marginBottom: "8px" }} /><div className="skeleton" style={{ width: "260px", height: "14px", borderRadius: "6px" }} /></div>
        <div className="skeleton" style={{ width: "140px", height: "36px", borderRadius: "6px" }} />
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px", marginBottom: "24px" }}>
        {[1,2,3].map(i => <div key={i} className="skeleton" style={{ height: "120px", borderRadius: "var(--radius)" }} />)}
      </div>
      <div className="skeleton" style={{ height: "250px", borderRadius: "var(--radius)" }} />
    </div>
  );
}

const card = { background: "var(--bg-card)", borderRadius: "var(--radius)", padding: "20px", boxShadow: "var(--shadow)", border: "1px solid var(--border)", marginBottom: "16px" };
const iconBadge = { width: "36px", height: "36px", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center" };
const sectionTitle = { fontSize: "14px", fontWeight: 600, color: "var(--fg-1)", marginBottom: "12px" };
const th = { textAlign: "left", padding: "12px 16px", fontWeight: 500, color: "var(--fg-3)", fontSize: "11px", borderBottom: "1px solid var(--border)", textTransform: "uppercase", letterSpacing: "0.5px" };
const td = { padding: "14px 16px", verticalAlign: "middle" };
const row = { borderBottom: "1px solid var(--border)", transition: "background 0.1s ease" };
const mono = { fontFamily: "var(--mono)", fontSize: "12px", color: "var(--fg-2)", background: "var(--bg-body)", padding: "3px 8px", borderRadius: "4px" };
const btnPrimary = { display: "inline-flex", alignItems: "center", gap: "6px", padding: "8px 16px", background: "var(--primary)", color: "#fff", border: "none", borderRadius: "6px", fontSize: "13px", fontWeight: 500, cursor: "pointer" };
const btnRestore = { display: "inline-flex", alignItems: "center", gap: "4px", padding: "5px 12px", background: "var(--warning-light)", color: "var(--warning)", border: "1px solid rgba(245,158,11,0.3)", borderRadius: "4px", fontSize: "11px", fontWeight: 500, cursor: "pointer" };
const btnDangerSmall = { display: "flex", alignItems: "center", justifyContent: "center", width: "30px", height: "30px", background: "none", border: "1px solid var(--border)", borderRadius: "6px", color: "var(--error)", cursor: "pointer", transition: "all 0.15s ease" };

// frontend/src/routes/dashboard/backup/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import Spinner from '$lib/components/Spinner.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import StatusBadge from '$lib/components/StatusBadge.svelte';
  import {
    Database, Download, Upload, RotateCcw, Trash2, Clock,
    FileJson, HardDrive, Shield, CheckCircle2, CircleAlert
  } from 'lucide-svelte/icons';

  interface BackupRecord {
    id: string;
    filename: string;
    size: number;
    type: string;
    status: string;
    createdAt: string;
  }

  let backups = $state<BackupRecord[]>([]);
  let loading = $state(true);
  let error = $state('');
  let exporting = $state(false);
  let importing = $state(false);
  let restoringId = $state<string | null>(null);

  async function loadBackups() {
    try {
      const data = await api.get<{ backups: BackupRecord[] }>('/api/backup');
      backups = data.backups || [];
    } catch (e: any) {
      error = e.message || 'Failed to load backups';
    }
  }

  onMount(async () => {
    loading = true;
    await loadBackups();
    loading = false;
  });

  async function exportConfig() {
    exporting = true;
    try {
      const data = await api.post<{ backup: BackupRecord }>('/api/backup/export');
      backups = [data.backup, ...backups];
    } catch (e: any) {
      error = e.message || 'Failed to export configuration';
    }
    exporting = false;
  }

  async function downloadExport(backupId: string) {
    try {
      const res = await api.raw(`/api/backup/${backupId}/download`);
      if (!res.ok) throw new Error('Download failed');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `lintasan-backup-${backupId}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e: any) {
      error = e.message || 'Failed to download backup';
    }
  }

  async function importConfig(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;

    importing = true;
    try {
      const text = await file.text();
      const config = JSON.parse(text);
      await api.post('/api/backup/import', config);
      await loadBackups();
    } catch (e: any) {
      error = e.message || 'Failed to import configuration';
    }
    importing = false;
    input.value = '';
  }

  async function restoreBackup(backupId: string) {
    if (!confirm('This will overwrite your current configuration. Are you sure?')) return;
    restoringId = backupId;
    try {
      await api.post(`/api/backup/${backupId}/restore`);
      backups = backups.map(b =>
        b.id === backupId ? { ...b, status: 'restored' } : b
      );
    } catch (e: any) {
      error = e.message || 'Failed to restore backup';
    }
    restoringId = null;
  }

  async function deleteBackup(backupId: string) {
    if (!confirm('Are you sure you want to delete this backup?')) return;
    try {
      await api.delete(`/api/backup/${backupId}`);
      backups = backups.filter(b => b.id !== backupId);
    } catch (e: any) {
      error = e.message || 'Failed to delete backup';
    }
  }

  function formatSize(bytes: number): string {
    if (bytes >= 1_048_576) return (bytes / 1_048_576).toFixed(1) + ' MB';
    if (bytes >= 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return bytes + ' B';
  }

  function formatDate(ts: string): string {
    try {
      return new Date(ts).toLocaleString(undefined, {
        month: 'short', day: 'numeric', year: 'numeric',
        hour: '2-digit', minute: '2-digit'
      });
    } catch {
      return ts;
    }
  }

  function getTypeIcon(type: string) {
    switch (type) {
      case 'full': return HardDrive;
      case 'config': return FileJson;
      case 'security': return Shield;
      default: return Database;
    }
  }
</script>

<svelte:head>
  <title>Backup — Lintasan</title>
</svelte:head>

<div style="display: flex; flex-direction: column; gap: 24px;">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div class="flex items-center gap-2.5">
      <div
        class="flex items-center justify-center rounded-xl"
        style="width: 40px; height: 40px; background: var(--color-success-light);"
      >
        <Database size={20} style="color: var(--color-success);" stroke-width={1.8} />
      </div>
      <div>
        <div style="font-size: 15px; font-weight: 600; color: var(--color-fg-0);">Backup & Restore</div>
        <div style="font-size: 12px; color: var(--color-fg-3);">Export, import and manage configuration backups</div>
      </div>
    </div>
  </div>

  <!-- Export/Import Actions -->
  <div class="grid gap-5" style="grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));">
    <!-- Export Card -->
    <div class="card">
      <div class="flex items-center gap-3" style="margin-bottom: 16px;">
        <div
          class="flex items-center justify-center rounded-lg"
          style="width: 36px; height: 36px; background: var(--color-primary-light);"
        >
          <Download size={18} style="color: var(--color-primary);" />
        </div>
        <div>
          <div style="font-size: 14px; font-weight: 600; color: var(--color-fg-0);">Export Configuration</div>
          <div style="font-size: 12px; color: var(--color-fg-3);">Create a snapshot of current settings</div>
        </div>
      </div>
      <button
        class="btn-primary flex items-center gap-1.5"
        onclick={exportConfig}
        disabled={exporting}
        style="width: 100%; justify-content: center;"
      >
        <Download size={14} />
        {exporting ? 'Exporting...' : 'Export Now'}
      </button>
    </div>

    <!-- Import Card -->
    <div class="card">
      <div class="flex items-center gap-3" style="margin-bottom: 16px;">
        <div
          class="flex items-center justify-center rounded-lg"
          style="width: 36px; height: 36px; background: var(--color-warning-light);"
        >
          <Upload size={18} style="color: var(--color-warning);" />
        </div>
        <div>
          <div style="font-size: 14px; font-weight: 600; color: var(--color-fg-0);">Import Configuration</div>
          <div style="font-size: 12px; color: var(--color-fg-3);">Restore from a JSON backup file</div>
        </div>
      </div>
      <label class="btn-secondary import-btn" style="width: 100%; justify-content: center; display: flex; align-items: center; gap: 6px; cursor: pointer;">
        <Upload size={14} />
        {importing ? 'Importing...' : 'Choose File'}
        <input
          type="file"
          accept=".json"
          onchange={importConfig}
          disabled={importing}
          style="display: none;"
        />
      </label>
    </div>
  </div>

  <!-- Backup History -->
  <div class="card" style="padding: 0; overflow: hidden;">
    <div
      class="flex items-center justify-between"
      style="padding: 18px 20px; border-bottom: 1px solid var(--color-border);"
    >
      <div class="flex items-center gap-2">
        <Clock size={16} style="color: var(--color-primary);" />
        <span style="font-size: 14px; font-weight: 600; color: var(--color-fg-0);">Backup History</span>
      </div>
      <button class="btn-secondary" onclick={loadBackups} style="padding: 5px 12px; font-size: 12px;">
        <RotateCcw size={12} style="display: inline; vertical-align: -1px;" />
        Refresh
      </button>
    </div>

    {#if loading}
      <Spinner />
    {:else if backups.length === 0}
      <EmptyState
        icon={Database}
        title="No backups yet"
        description="Create an export to save your current configuration."
      />
    {:else}
      <div style="overflow-x: auto;">
        <table class="backups-table">
          <thead>
            <tr>
              <th style="width: 220px;">Name</th>
              <th style="width: 100px;">Type</th>
              <th style="width: 90px;">Size</th>
              <th style="width: 100px;">Status</th>
              <th style="width: 160px;">Created</th>
              <th style="width: 140px;">Actions</th>
            </tr>
          </thead>
          <tbody>
            {#each backups as backup, i (backup.id)}
              <tr style="animation: fadeInUp {0.3 + i * 0.03}s ease-out;">
                <td>
                  <div class="flex items-center gap-2.5">
                    <div
                      class="flex items-center justify-center rounded-lg"
                      style="width: 30px; height: 30px; background: var(--color-bg-body); flex-shrink: 0;"
                    >
                      {#if backup.type === 'full'}
                        <HardDrive size={14} style="color: var(--color-fg-2);" />
                      {:else if backup.type === 'config'}
                        <FileJson size={14} style="color: var(--color-fg-2);" />
                      {:else if backup.type === 'security'}
                        <Shield size={14} style="color: var(--color-fg-2);" />
                      {:else}
                        <Database size={14} style="color: var(--color-fg-2);" />
                      {/if}
                    </div>
                    <span class="font-mono" style="font-size: 12px; font-weight: 500; color: var(--color-fg-0);">
                      {backup.filename}
                    </span>
                  </div>
                </td>
                <td>
                  <span class="badge" style="font-size: 10px; padding: 2px 8px; background: var(--color-info-light); color: var(--color-info);">
                    {backup.type}
                  </span>
                </td>
                <td>
                  <span class="font-mono" style="font-size: 12px; color: var(--color-fg-2);">
                    {formatSize(backup.size)}
                  </span>
                </td>
                <td>
                  <StatusBadge status={backup.status} />
                </td>
                <td>
                  <span style="font-size: 12px; color: var(--color-fg-3);">
                    {formatDate(backup.createdAt)}
                  </span>
                </td>
                <td>
                  <div class="flex items-center gap-1">
                    <button
                      class="btn-icon"
                      style="color: var(--color-primary);"
                      onclick={() => downloadExport(backup.id)}
                      title="Download backup"
                    >
                      <Download size={14} />
                    </button>
                    <button
                      class="btn-icon"
                      style="color: var(--color-success);"
                      onclick={() => restoreBackup(backup.id)}
                      disabled={restoringId === backup.id}
                      title="Restore from this backup"
                    >
                      <RotateCcw size={14} class={restoringId === backup.id ? 'spin-icon' : ''} />
                    </button>
                    <button
                      class="btn-icon"
                      style="color: var(--color-error);"
                      onclick={() => deleteBackup(backup.id)}
                      title="Delete backup"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>

      <!-- Table Footer -->
      <div
        class="flex items-center justify-between"
        style="padding: 12px 16px; border-top: 1px solid var(--color-border); background: var(--color-bg-body);"
      >
        <span style="font-size: 12px; color: var(--color-fg-3);">
          {backups.length} backup{backups.length !== 1 ? 's' : ''}
        </span>
      </div>
    {/if}
  </div>

  {#if error}
    <div
      class="flex items-center gap-2"
      style="
        padding: 12px 16px; border-radius: var(--radius-sm);
        background: var(--color-error-light); color: var(--color-error);
        font-size: 13px; font-weight: 500;
      "
    >
      {error}
      <button style="margin-left: auto; cursor: pointer; color: var(--color-error); background: none; border: none;" onclick={() => error = ''}>&times;</button>
    </div>
  {/if}
</div>

<style>
  .backups-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }
  .backups-table th {
    padding: 10px 16px;
    text-align: left;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--color-fg-3);
    background: var(--color-bg-body);
    border-bottom: 1px solid var(--color-border);
    white-space: nowrap;
  }
  .backups-table td {
    padding: 12px 16px;
    border-bottom: 1px solid var(--color-border-light);
    vertical-align: middle;
  }
  .backups-table tbody tr {
    transition: var(--transition);
  }
  .backups-table tbody tr:hover {
    background: var(--color-primary-light);
  }
  .backups-table tbody tr:last-child td {
    border-bottom: none;
  }
  .btn-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: var(--radius-sm);
    border: none;
    background: transparent;
    cursor: pointer;
    transition: var(--transition);
  }
  .btn-icon:hover {
    background: var(--color-bg-sidebar-hover);
  }
  .btn-icon:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  :global(.spin-icon) {
    animation: spin 1s linear infinite;
  }
  @keyframes spin {
    to { transform: rotate(360deg); }
  }
  .import-btn {
    font-size: 13px;
  }
</style>
