// frontend/src/routes/dashboard/plugins/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import Spinner from '$lib/components/Spinner.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import {
    Puzzle, Store, Sparkles, Settings, Trash2, Power,
    PowerOff, Search, Download, Tag, ChevronRight,
    CircleAlert, CheckCircle2, Box, Info, X, Loader2, Wand2, Eye
  } from 'lucide-svelte/icons';

  interface Plugin {
    id: string;
    name: string;
    description: string;
    version: string;
    enabled: boolean;
    author?: string;
    categories?: string[];
    installedAt?: string;
    config?: Record<string, unknown>;
  }

  interface StorePlugin {
    id: string;
    name: string;
    description: string;
    version: string;
    author: string;
    categories: string[];
    downloads: number;
    installed: boolean;
  }

  let activeTab = $state<'installed' | 'store' | 'generate'>('installed');
  let installedPlugins = $state<Plugin[]>([]);
  let storePlugins = $state<StorePlugin[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);

  // Installed tab state
  let configuringPlugin = $state<Plugin | null>(null);
  let configJson = $state('');
  let togglingPlugin = $state<string | null>(null);
  let uninstallingPlugin = $state<string | null>(null);

  // Store tab state
  let storeSearch = $state('');
  let storeCategory = $state('all');
  let installingPlugin = $state<string | null>(null);

  // AI Generate tab state
  let generatePrompt = $state('');
  let generating = $state(false);
  let generatedPlugin = $state<{ name: string; description: string; code: string } | null>(null);
  let generateError = $state<string | null>(null);

  const categoryColors: Record<string, string> = {
    'utility': 'var(--color-info-light)',
    'auth': 'var(--color-success-light)',
    'logging': 'var(--color-warning-light)',
    'caching': 'var(--color-purple-light)',
    'transform': 'var(--color-primary-light)',
    'monitoring': 'var(--color-error-light)',
    'security': 'var(--color-error-light)',
    'integration': 'var(--color-info-light)',
  };
  const categoryFg: Record<string, string> = {
    'utility': 'var(--color-info)',
    'auth': 'var(--color-success)',
    'logging': 'var(--color-warning)',
    'caching': 'var(--color-purple)',
    'transform': 'var(--color-primary)',
    'monitoring': 'var(--color-error)',
    'security': 'var(--color-error)',
    'integration': 'var(--color-info)',
  };

  async function loadInstalled() {
    try {
      const res = await api.get<any>('/api/plugins');
      installedPlugins = res?.data || res?.plugins || [];
    } catch (e: any) {
      error = e.message || 'Failed to load plugins';
    }
  }

  async function loadStore() {
    try {
      const res = await api.get<any>('/api/plugins/store');
      const raw = res?.data || res?.plugins || [];
      storePlugins = Array.isArray(raw) ? raw.map((w: any) => ({
        id: w.id || w.name || '',
        name: w.name || '',
        description: w.description || '',
        version: w.version || '1.0.0',
        author: w.author || 'Unknown',
        categories: Array.isArray(w.categories) ? w.categories : (w.category ? [w.category] : []),
        downloads: w.downloads || 0,
        installed: !!w.installed
      })) : [];
    } catch {
      // Store may not be available
    }
  }

  onMount(async () => {
    loading = true;
    await Promise.all([loadInstalled(), loadStore()]);
    loading = false;
  });

  async function togglePlugin(plugin: Plugin) {
    togglingPlugin = plugin.id;
    try {
      await api.patch(`/api/plugins/${plugin.id}`, { enabled: !plugin.enabled });
      plugin.enabled = !plugin.enabled;
      installedPlugins = [...installedPlugins];
    } catch (e: any) {
      error = e.message || 'Failed to toggle plugin';
    } finally {
      togglingPlugin = null;
    }
  }

  async function uninstallPlugin(plugin: Plugin) {
    if (!confirm(`Uninstall "${plugin.name}"? This cannot be undone.`)) return;
    uninstallingPlugin = plugin.id;
    try {
      await api.delete(`/api/plugins/${plugin.id}`);
      installedPlugins = installedPlugins.filter(p => p.id !== plugin.id);
    } catch (e: any) {
      error = e.message || 'Failed to uninstall plugin';
    } finally {
      uninstallingPlugin = null;
    }
  }

  function openConfig(plugin: Plugin) {
    configuringPlugin = plugin;
    configJson = JSON.stringify(plugin.config || {}, null, 2);
  }

  function closeConfigModal() {
    configuringPlugin = null;
  }

  function handleConfigOverlayKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape' || event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      closeConfigModal();
    }
  }

  function stopConfigClose(event: MouseEvent) {
    event.stopPropagation();
  }

  function stopConfigCloseKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      event.stopPropagation();
      closeConfigModal();
    }
  }

  async function saveConfig() {
    if (!configuringPlugin) return;
    try {
      const parsed = JSON.parse(configJson);
      await api.patch(`/api/plugins/${configuringPlugin.id}/config`, { config: parsed });
      configuringPlugin.config = parsed;
      installedPlugins = [...installedPlugins];
      closeConfigModal();
    } catch (e: any) {
      error = e.message || 'Invalid JSON or failed to save config';
    }
  }

  async function installFromStore(plugin: StorePlugin) {
    installingPlugin = plugin.id;
    try {
      await api.post(`/api/plugins/install`, { pluginId: plugin.id });
      plugin.installed = true;
      storePlugins = [...storePlugins];
      await loadInstalled();
    } catch (e: any) {
      error = e.message || 'Failed to install plugin';
    } finally {
      installingPlugin = null;
    }
  }

  async function generatePlugin() {
    if (!generatePrompt.trim()) return;
    generating = true;
    generateError = null;
    generatedPlugin = null;
    try {
      const data = await api.post<{ name: string; description: string; code: string }>(
        '/api/plugins/generate',
        { prompt: generatePrompt }
      );
      generatedPlugin = data;
    } catch (e: any) {
      generateError = e.message || 'Failed to generate plugin';
    } finally {
      generating = false;
    }
  }

  let filteredStorePlugins = $derived(
    storePlugins.filter(p => {
      const matchesSearch = !storeSearch.trim() ||
        p.name.toLowerCase().includes(storeSearch.toLowerCase()) ||
        p.description.toLowerCase().includes(storeSearch.toLowerCase());
      const matchesCategory = storeCategory === 'all' ||
        (p.categories || []).includes(storeCategory);
      return matchesSearch && matchesCategory;
    })
  );

  let allCategories = $derived(
    [...new Set(storePlugins.flatMap(p => p.categories || []))].sort()
  );

  const tabs = [
    { id: 'installed' as const, label: 'Installed', icon: Puzzle },
    { id: 'store' as const, label: 'Store', icon: Store },
    { id: 'generate' as const, label: 'AI Generate', icon: Sparkles },
  ];
</script>

<svelte:head>
  <title>Plugins — Lintasan</title>
</svelte:head>

<div style="display: flex; flex-direction: column; gap: 24px;">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h2 style="font-size: 20px; font-weight: 700; color: var(--color-fg-0); letter-spacing: -0.3px;">
        Plugin Management
      </h2>
      <p style="font-size: 13px; color: var(--color-fg-2); margin-top: 2px;">
        Extend your gateway with plugins, browse the store, or generate with AI
      </p>
    </div>
  </div>

  <!-- Tabs -->
  <div class="card" style="padding: 0; overflow: hidden;">
    <div
      class="flex"
      style="border-bottom: 1px solid var(--color-border);"
    >
      {#each tabs as tab}
        <button
          class="tab-btn"
          class:active={activeTab === tab.id}
          onclick={() => activeTab = tab.id}
        >
          <tab.icon size={16} />
          <span>{tab.label}</span>
        </button>
      {/each}
    </div>

    <div style="padding: 24px;">
      {#if loading}
        <Spinner />
      {:else}
        <!-- INSTALLED TAB -->
        {#if activeTab === 'installed'}
          {#if installedPlugins.length === 0}
            <EmptyState
              icon={Puzzle}
              title="No plugins installed"
              description="Browse the store or generate a plugin with AI to get started"
            />
          {:else}
            <div style="display: flex; flex-direction: column; gap: 12px;">
              {#each installedPlugins as plugin, i}
                <div
                  class="plugin-card"
                  style="animation: fadeInUp {0.3 + i * 0.05}s ease-out;"
                >
                  <div class="flex items-start justify-between">
                    <div class="flex items-start gap-3" style="flex: 1; min-width: 0;">
                      <div
                        class="flex items-center justify-center rounded-lg"
                        style="width: 40px; height: 40px; background: {plugin.enabled ? 'var(--color-primary-light)' : 'var(--color-bg-body)'}; flex-shrink: 0;"
                      >
                        <Puzzle
                          size={20}
                          style="color: {plugin.enabled ? 'var(--color-primary)' : 'var(--color-fg-3)'};"
                        />
                      </div>
                      <div style="min-width: 0;">
                        <div class="flex items-center gap-2">
                          <span style="font-size: 14px; font-weight: 600; color: var(--color-fg-0);">
                            {plugin.name}
                          </span>
                          <span
                            style="font-size: 11px; color: var(--color-fg-3); font-family: var(--font-mono);"
                          >v{plugin.version}</span>
                        </div>
                        <p style="font-size: 13px; color: var(--color-fg-2); margin-top: 2px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                          {plugin.description}
                        </p>
                        {#if plugin.categories && plugin.categories.length > 0}
                          <div class="flex items-center gap-1.5" style="margin-top: 6px;">
                            {#each plugin.categories as cat}
                              <span
                                class="badge"
                                style="font-size: 10px; padding: 2px 8px; background: {categoryColors[cat] || 'var(--color-border-light)'}; color: {categoryFg[cat] || 'var(--color-fg-2)'};"
                              >{cat}</span>
                            {/each}
                          </div>
                        {/if}
                      </div>
                    </div>

                    <div class="flex items-center gap-2" style="flex-shrink: 0;">
                      <!-- Enable/Disable Toggle -->
                      <button
                        class="action-btn"
                        class:enabled={plugin.enabled}
                        onclick={() => togglePlugin(plugin)}
                        disabled={togglingPlugin === plugin.id}
                        title={plugin.enabled ? 'Disable plugin' : 'Enable plugin'}
                      >
                        {#if togglingPlugin === plugin.id}
                          <Loader2 size={14} class="spin-icon" />
                        {:else if plugin.enabled}
                          <Power size={14} />
                        {:else}
                          <PowerOff size={14} />
                        {/if}
                      </button>

                      <!-- Config -->
                      <button
                        class="action-btn"
                        onclick={() => openConfig(plugin)}
                        title="Configure plugin"
                      >
                        <Settings size={14} />
                      </button>

                      <!-- Uninstall -->
                      <button
                        class="action-btn danger"
                        onclick={() => uninstallPlugin(plugin)}
                        disabled={uninstallingPlugin === plugin.id}
                        title="Uninstall plugin"
                      >
                        {#if uninstallingPlugin === plugin.id}
                          <Loader2 size={14} class="spin-icon" />
                        {:else}
                          <Trash2 size={14} />
                        {/if}
                      </button>
                    </div>
                  </div>
                </div>
              {/each}
            </div>
          {/if}

        <!-- STORE TAB -->
        {:else if activeTab === 'store'}
          <!-- Search & Filter -->
          <div class="flex items-center gap-3 flex-wrap" style="margin-bottom: 20px;">
            <div class="search-wrapper">
              <Search size={14} style="color: var(--color-fg-3); position: absolute; left: 10px; top: 50%; transform: translateY(-50%); pointer-events: none;" />
              <input
                class="input-field search-input"
                placeholder="Search plugins..."
                bind:value={storeSearch}
              />
            </div>
            <select
              class="input-field"
              style="width: 160px; font-size: 12px; padding: 7px 10px;"
              bind:value={storeCategory}
            >
              <option value="all">All Categories</option>
              {#each allCategories as cat}
                <option value={cat}>{cat.charAt(0).toUpperCase() + cat.slice(1)}</option>
              {/each}
            </select>
          </div>

          {#if filteredStorePlugins.length === 0}
            <EmptyState
              icon={Store}
              title="No plugins found"
              description={storeSearch.trim() ? 'Try adjusting your search terms' : 'The plugin store is empty or unavailable'}
            />
          {:else}
            <div
              class="grid gap-4"
              style="grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));"
            >
              {#each filteredStorePlugins as plugin, i}
                <div
                  class="store-card"
                  style="animation: fadeInUp {0.3 + i * 0.05}s ease-out;"
                >
                  <div class="flex items-start justify-between" style="margin-bottom: 12px;">
                    <div>
                      <div style="font-size: 14px; font-weight: 600; color: var(--color-fg-0);">
                        {plugin.name}
                      </div>
                      <div style="font-size: 12px; color: var(--color-fg-3); margin-top: 2px;">
                        by {plugin.author} · v{plugin.version}
                      </div>
                    </div>
                    <div class="flex items-center gap-1" style="font-size: 11px; color: var(--color-fg-3);">
                      <Download size={12} />
                      {plugin.downloads.toLocaleString()}
                    </div>
                  </div>

                  <p style="font-size: 13px; color: var(--color-fg-2); line-height: 1.5; margin-bottom: 12px;">
                    {plugin.description}
                  </p>

                  <div class="flex items-center justify-between">
                    <div class="flex items-center gap-1.5 flex-wrap">
                      {#each (plugin.categories || []) as cat}
                        <span
                          class="badge"
                          style="font-size: 10px; padding: 2px 8px; background: {categoryColors[cat] || 'var(--color-border-light)'}; color: {categoryFg[cat] || 'var(--color-fg-2)'};"
                        >{cat}</span>
                      {/each}
                    </div>

                    {#if plugin.installed}
                      <span class="flex items-center gap-1" style="font-size: 12px; color: var(--color-success); font-weight: 500;">
                        <CheckCircle2 size={14} />
                        Installed
                      </span>
                    {:else}
                      <button
                        class="btn-primary"
                        style="padding: 6px 14px; font-size: 12px; display: flex; align-items: center; gap: 4px;"
                        onclick={() => installFromStore(plugin)}
                        disabled={installingPlugin === plugin.id}
                      >
                        {#if installingPlugin === plugin.id}
                          <Loader2 size={12} class="spin-icon" />
                          Installing...
                        {:else}
                          <Download size={12} />
                          Install
                        {/if}
                      </button>
                    {/if}
                  </div>
                </div>
              {/each}
            </div>
          {/if}

        <!-- AI GENERATE TAB -->
        {:else if activeTab === 'generate'}
          <div style="max-width: 720px;">
            <div style="margin-bottom: 20px;">
              <label
                for="generate-input"
                style="display: block; font-size: 13px; font-weight: 600; color: var(--color-fg-1); margin-bottom: 8px;"
              >
                Describe your plugin
              </label>
              <textarea
                id="generate-input"
                class="input-field"
                rows="4"
                placeholder="e.g., A rate-limiter plugin that limits requests to 100 per minute per API key, with configurable window and burst size..."
                bind:value={generatePrompt}
                style="resize: vertical;"
              ></textarea>
            </div>

            <button
              class="btn-primary"
              onclick={generatePlugin}
              disabled={generating || !generatePrompt.trim()}
              style="display: flex; align-items: center; gap: 8px; margin-bottom: 24px;"
            >
              {#if generating}
                <Loader2 size={16} class="spin-icon" />
                Generating...
              {:else}
                <Wand2 size={16} />
                Generate Plugin
              {/if}
            </button>

            {#if generateError}
              <div
                class="flex items-center gap-2"
                style="
                  padding: 12px 16px; border-radius: var(--radius-sm);
                  background: var(--color-error-light); color: var(--color-error);
                  font-size: 13px; font-weight: 500; margin-bottom: 20px;
                "
              >
                <CircleAlert size={16} />
                {generateError}
              </div>
            {/if}

            {#if generatedPlugin}
              <div class="card" style="animation: fadeInUp 0.4s ease-out;">
                <div class="flex items-center gap-2" style="margin-bottom: 16px;">
                  <Sparkles size={18} style="color: var(--color-purple);" />
                  <span style="font-size: 16px; font-weight: 600; color: var(--color-fg-0);">
                    {generatedPlugin.name}
                  </span>
                </div>

                <p style="font-size: 13px; color: var(--color-fg-2); margin-bottom: 16px; line-height: 1.6;">
                  {generatedPlugin.description}
                </p>

                <div
                  style="
                    background: var(--color-bg-body);
                    border: 1px solid var(--color-border);
                    border-radius: var(--radius-sm);
                    padding: 16px;
                    overflow-x: auto;
                    margin-bottom: 16px;
                  "
                >
                  <pre style="font-family: var(--font-mono); font-size: 12px; color: var(--color-fg-1); line-height: 1.6; margin: 0; white-space: pre-wrap;">{generatedPlugin.code}</pre>
                </div>

                <div class="flex items-center gap-2">
                  <button class="btn-primary" style="display: flex; align-items: center; gap: 6px;">
                    <Download size={14} />
                    Install Plugin
                  </button>
                  <button class="btn-secondary" style="display: flex; align-items: center; gap: 6px;">
                    <Eye size={14} />
                    Preview
                  </button>
                </div>
              </div>
            {/if}
          </div>
        {/if}
      {/if}
    </div>
  </div>

  <!-- Error banner -->
  {#if error}
    <div
      class="flex items-center gap-2"
      style="
        padding: 12px 16px; border-radius: var(--radius-sm);
        background: var(--color-error-light); color: var(--color-error);
        font-size: 13px; font-weight: 500;
      "
    >
      <CircleAlert size={16} />
      {error}
      <button
        style="margin-left: auto; cursor: pointer; color: var(--color-error); background: none; border: none;"
        onclick={() => error = null}
      >&times;</button>
    </div>
  {/if}
</div>

<!-- Config Modal -->
{#if configuringPlugin}
  <div
    class="modal-backdrop"
    role="button"
    tabindex="0"
    aria-label="Close plugin config modal"
    onclick={closeConfigModal}
    onkeydown={handleConfigOverlayKeydown}
  >
    <div
      class="modal-card card"
      role="dialog"
      aria-modal="true"
      aria-label="Plugin configuration dialog"
      tabindex="-1"
      onclick={stopConfigClose}
      onkeydown={stopConfigCloseKeydown}
      style="animation: fadeInScale 0.3s ease-out;"
    >
      <div class="flex items-center justify-between" style="margin-bottom: 16px;">
        <div class="flex items-center gap-2">
          <Settings size={18} style="color: var(--color-primary);" />
          <span style="font-size: 15px; font-weight: 600; color: var(--color-fg-0);">
            Configure {configuringPlugin.name}
          </span>
        </div>
        <button
          class="action-btn"
          onclick={closeConfigModal}
        >
          <X size={16} />
        </button>
      </div>

      <textarea
        class="input-field"
        rows="10"
        bind:value={configJson}
        style="font-family: var(--font-mono); font-size: 12px; resize: vertical;"
          placeholder="&#123;&#125;"
      ></textarea>

      <div class="flex items-center justify-end gap-2" style="margin-top: 16px;">
        <button class="btn-secondary" onclick={closeConfigModal}>Cancel</button>
        <button class="btn-primary" onclick={saveConfig}>Save Configuration</button>
      </div>
    </div>
  </div>
{/if}

<style>
  .tab-btn {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 14px 20px;
    font-size: 13px;
    font-weight: 500;
    color: var(--color-fg-2);
    background: transparent;
    border: none;
    border-bottom: 2px solid transparent;
    cursor: pointer;
    transition: var(--transition);
  }
  .tab-btn:hover {
    color: var(--color-fg-0);
    background: var(--color-bg-body);
  }
  .tab-btn.active {
    color: var(--color-primary);
    border-bottom-color: var(--color-primary);
    font-weight: 600;
  }

  .plugin-card {
    padding: 16px;
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    background: var(--color-bg-card);
    transition: var(--transition);
  }
  .plugin-card:hover {
    border-color: var(--color-primary);
    box-shadow: 0 0 0 3px var(--color-primary-glow);
  }

  .store-card {
    padding: 20px;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    background: var(--color-bg-card);
    transition: var(--transition);
  }
  .store-card:hover {
    border-color: var(--color-primary);
    box-shadow: var(--shadow-md);
  }

  .action-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: var(--radius-sm);
    border: 1px solid var(--color-border);
    background: transparent;
    color: var(--color-fg-2);
    cursor: pointer;
    transition: var(--transition);
  }
  .action-btn:hover {
    background: var(--color-bg-body);
    color: var(--color-fg-0);
    border-color: var(--color-fg-3);
  }
  .action-btn.enabled {
    background: var(--color-success-light);
    color: var(--color-success);
    border-color: var(--color-success);
  }
  .action-btn.danger:hover {
    background: var(--color-error-light);
    color: var(--color-error);
    border-color: var(--color-error);
  }
  .action-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .search-wrapper {
    position: relative;
    flex: 1;
    min-width: 200px;
    max-width: 360px;
  }
  .search-input {
    padding-left: 32px !important;
  }

  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;
    padding: 24px;
  }
  .modal-card {
    width: 100%;
    max-width: 560px;
    max-height: 80vh;
    overflow-y: auto;
  }

  :global(.spin-icon) {
    animation: spin 0.8s linear infinite;
  }
</style>

// web/frontend/src/pages/Plugins.jsx

import { useState, useEffect } from "react";

const TABS = [
  { id: "installed", label: "My Plugins" },
  { id: "store", label: "Store" },
  { id: "generate", label: "✨ AI Generate" },
];

const CATEGORY_COLORS = {
  security: { bg: "rgba(239,68,68,0.1)", color: "#ef4444", border: "rgba(239,68,68,0.2)" },
  monitoring: { bg: "rgba(59,130,246,0.1)", color: "#3b82f6", border: "rgba(59,130,246,0.2)" },
  optimization: { bg: "rgba(16,185,129,0.1)", color: "#10b981", border: "rgba(16,185,129,0.2)" },
  utility: { bg: "rgba(139,92,246,0.1)", color: "#8b5cf6", border: "rgba(139,92,246,0.2)" },
  integration: { bg: "rgba(245,158,11,0.1)", color: "#f59e0b", border: "rgba(245,158,11,0.2)" },
};

export default function PluginsPage() {
  const [tab, setTab] = useState("installed");

  return (
    <div className="fade-in">
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
        <div>
          <h1 style={{ fontSize: "18px", fontWeight: 600, color: "var(--fg-0)", marginBottom: "4px" }}>Plugins</h1>
          <p style={{ fontSize: "13px", color: "var(--fg-3)" }}>Install, manage, and create plugins for the proxy pipeline</p>
        </div>
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", gap: "0", marginBottom: "24px", borderBottom: "1px solid var(--border)" }}>
        {TABS.map(t => (
          <button key={t.id} onClick={() => setTab(t.id)} style={{
            padding: "10px 20px", fontSize: "13px", fontWeight: tab === t.id ? 600 : 400,
            color: tab === t.id ? "var(--primary)" : "var(--fg-3)",
            background: "none", border: "none", borderBottom: tab === t.id ? "2px solid var(--primary)" : "2px solid transparent",
            cursor: "pointer", transition: "all 0.15s ease",
          }}>
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      {tab === "installed" && <InstalledTab />}
      {tab === "store" && <StoreTab />}
      {tab === "generate" && <GenerateTab />}
    </div>
  );
}

/* ==================== INSTALLED TAB ==================== */
function InstalledTab() {
  const [plugins, setPlugins] = useState([]);
  const [loading, setLoading] = useState(true);
  const [viewing, setViewing] = useState(null);
  const [saving, setSaving] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ name: "", code: "" });
  const [creating, setCreating] = useState(false);

  const load = () => {
    fetch("/api/plugins", { credentials: "include" })
      .then(r => r.json())
      .then(d => { setPlugins(d.plugins || d.data || []); setLoading(false); })
      .catch(() => setLoading(false));
  };
  useEffect(() => { load(); }, []);

  const togglePlugin = async (name, enabled) => {
    await fetch("/api/plugins", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ name, enabled: !enabled }) });
    load();
  };

  const deletePlugin = async (name) => {
    if (!confirm(`Delete plugin "${name}"?`)) return;
    await fetch("/api/plugins", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ action: "delete", name }) });
    load();
  };

  const viewSource = async (name) => {
    const res = await fetch(`/api/plugins?name=${encodeURIComponent(name)}`, { credentials: "include" });
    const data = await res.json();
    if (data.code) setViewing({ name: data.name, code: data.code });
  };

  const saveSource = async () => {
    if (!viewing) return;
    setSaving(true);
    const res = await fetch("/api/plugins", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ action: "update", name: viewing.name, code: viewing.code }) });
    const data = await res.json();
    setSaving(false);
    if (data.ok) { setViewing(null); load(); }
  };

  const createPlugin = async () => {
    if (!form.name) return;
    setCreating(true);
    const code = form.code || generateTemplate(form.name);
    await fetch("/api/plugins", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ action: "create", name: form.name, code }) });
    setCreating(false);
    setShowCreate(false);
    setForm({ name: "", code: "" });
    load();
  };

  if (loading) return <div className="skeleton" style={{ height: "200px", borderRadius: "var(--radius)" }} />;

  const enabledCount = plugins.filter(p => p.enabled).length;

  return (
    <>
      {/* Stats */}
      <div className="responsive-grid" style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "1px", background: "var(--border)", borderRadius: "var(--radius)", overflow: "hidden", border: "1px solid var(--border)", marginBottom: "20px" }}>
        <div style={metricCell}><p style={metricLabel}>Installed</p><p style={metricValue}>{plugins.length}</p></div>
        <div style={metricCell}><p style={metricLabel}>Enabled</p><p style={metricValue}>{enabledCount}</p></div>
        <div style={metricCell}><p style={metricLabel}>Disabled</p><p style={metricValue}>{plugins.length - enabledCount}</p></div>
      </div>

      {/* Actions */}
      <div style={{ marginBottom: "16px" }}>
        <button onClick={() => setShowCreate(!showCreate)} style={btnPrimary}>{showCreate ? "✕ Cancel" : "+ Create Manually"}</button>
      </div>

      {/* Create Form */}
      {showCreate && (
        <div style={card} className="fade-in">
          <div style={{ display: "grid", gridTemplateColumns: "200px 1fr", gap: "14px", marginBottom: "14px" }}>
            <div><label style={labelSt}>Name</label><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} style={input} placeholder="my-plugin" /></div>
            <div><label style={labelSt}>Code (empty = template)</label><textarea value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} style={{ ...input, minHeight: "120px", fontFamily: "var(--mono)", fontSize: "12px" }} placeholder="Leave empty for starter template..." /></div>
          </div>
          <button onClick={createPlugin} disabled={creating || !form.name} style={{ ...btnPrimary, opacity: (!form.name) ? 0.5 : 1 }}>{creating ? "Creating..." : "Create"}</button>
        </div>
      )}

      {/* Source Editor Modal */}
      {viewing && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center", padding: "24px" }} onClick={() => setViewing(null)}>
          <div style={{ background: "var(--bg-card)", borderRadius: "var(--radius-lg)", width: "100%", maxWidth: "720px", maxHeight: "80vh", display: "flex", flexDirection: "column", boxShadow: "var(--shadow-lg)", border: "1px solid var(--border)" }} onClick={e => e.stopPropagation()}>
            <div style={{ padding: "16px 20px", borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <p style={{ fontSize: "15px", fontWeight: 600, color: "var(--fg-0)" }}>{viewing.name}.js</p>
              <div style={{ display: "flex", gap: "8px" }}>
                <button onClick={saveSource} disabled={saving} style={btnPrimary}>{saving ? "Saving..." : "Save"}</button>
                <button onClick={() => setViewing(null)} style={btnSecondary}>Close</button>
              </div>
            </div>
            <div style={{ flex: 1, overflow: "auto", padding: "16px" }}>
              <textarea value={viewing.code} onChange={e => setViewing({ ...viewing, code: e.target.value })} style={{ width: "100%", minHeight: "400px", padding: "14px", background: "var(--bg-body)", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)", color: "var(--fg-0)", fontSize: "12px", fontFamily: "var(--mono)", lineHeight: "1.7", resize: "vertical", outline: "none" }} />
            </div>
          </div>
        </div>
      )}

      {/* Plugin List */}
      {plugins.length === 0 ? (
        <div style={{ ...card, padding: "48px", textAlign: "center" }}>
          <p style={{ fontSize: "14px", color: "var(--fg-2)" }}>No plugins installed yet. Browse the Store or use AI Generate.</p>
        </div>
      ) : (
        <div className="responsive-grid" style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "14px" }}>
          {plugins.map(p => (
            <div key={p.name} style={{ ...card, marginBottom: 0, padding: "16px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "10px" }}>
                <div style={{ width: "32px", height: "32px", borderRadius: "8px", background: p.enabled ? "var(--success-light)" : "var(--bg-body)", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid " + (p.enabled ? "rgba(16,185,129,0.2)" : "var(--border)") }}>
                  <IconPlugin color={p.enabled ? "var(--success)" : "var(--fg-3)"} />
                </div>
                <div style={{ flex: 1 }}>
                  <p style={{ fontSize: "13px", fontWeight: 600, color: "var(--fg-0)" }}>{p.name}</p>
                  {p.description && <p style={{ fontSize: "11px", color: "var(--fg-3)" }}>{p.description}</p>}
                </div>
              </div>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: "10px", borderTop: "1px solid var(--border)" }}>
                <div style={{ display: "flex", gap: "6px" }}>
                  <button onClick={() => viewSource(p.name)} style={btnSmall} title="Source"><IconCode /></button>
                  <button onClick={() => deletePlugin(p.name)} style={{ ...btnSmall, background: "var(--error-light)", borderColor: "rgba(239,68,68,0.2)" }} title="Delete"><IconTrash /></button>
                </div>
                <button onClick={() => togglePlugin(p.name, p.enabled)} style={{ position: "relative", width: "36px", height: "20px", borderRadius: "10px", border: "none", cursor: "pointer", background: p.enabled ? "var(--primary)" : "var(--border)", transition: "background 0.2s", padding: 0 }}>
                  <div style={{ position: "absolute", top: "3px", left: p.enabled ? "19px" : "3px", width: "14px", height: "14px", borderRadius: "50%", background: "#fff", boxShadow: "0 1px 3px rgba(0,0,0,0.2)", transition: "left 0.2s" }} />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </>
  );
}

/* ==================== STORE TAB ==================== */
function StoreTab() {
  const [plugins, setPlugins] = useState([]);
  const [categories, setCategories] = useState([]);
  const [activeCategory, setActiveCategory] = useState("all");
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [installedNames, setInstalledNames] = useState(new Set());
  const [installing, setInstalling] = useState(null);

  useEffect(() => {
    Promise.all([
      fetch("/api/plugins/store", { credentials: "include" }).then(r => r.json()),
      fetch("/api/plugins", { credentials: "include" }).then(r => r.json()),
    ]).then(([store, installed]) => {
      setPlugins(store.plugins || []);
      setCategories(store.categories || []);
      const names = new Set((installed.plugins || []).map(p => p.name));
      setInstalledNames(names);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  const install = async (id) => {
    setInstalling(id);
    const res = await fetch("/api/plugins/store", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ action: "install", id }) });
    const data = await res.json();
    if (data.ok) setInstalledNames(prev => new Set([...prev, data.name || id]));
    setInstalling(null);
  };

  if (loading) return <div className="skeleton" style={{ height: "200px", borderRadius: "var(--radius)" }} />;

  const filtered = plugins.filter(p => {
    if (activeCategory !== "all" && p.category !== activeCategory) return false;
    if (search && !p.name.includes(search.toLowerCase()) && !p.description.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  return (
    <>
      {/* Filters */}
      <div style={{ display: "flex", gap: "10px", marginBottom: "16px", flexWrap: "wrap", alignItems: "center" }}>
        <input value={search} onChange={e => setSearch(e.target.value)} style={{ ...input, width: "220px" }} placeholder="Search plugins..." />
        <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
          <button onClick={() => setActiveCategory("all")} style={{ ...tagBtn, ...(activeCategory === "all" ? tagActive : {}) }}>All</button>
          {categories.map(c => (
            <button key={c} onClick={() => setActiveCategory(c)} style={{ ...tagBtn, ...(activeCategory === c ? tagActive : {}) }}>{c}</button>
          ))}
        </div>
      </div>

      {/* Grid */}
      <div className="responsive-grid" style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "14px" }}>
        {filtered.map(p => {
          const catColor = CATEGORY_COLORS[p.category] || CATEGORY_COLORS.utility;
          const isInstalled = installedNames.has(p.name) || installedNames.has(p.id);
          return (
            <div key={p.id} style={{ ...card, marginBottom: 0, padding: "16px" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "8px" }}>
                <div>
                  <p style={{ fontSize: "13px", fontWeight: 600, color: "var(--fg-0)", marginBottom: "4px" }}>{p.name}</p>
                  <p style={{ fontSize: "12px", color: "var(--fg-3)", lineHeight: "1.4" }}>{p.description}</p>
                </div>
              </div>
              <div style={{ display: "flex", gap: "6px", marginBottom: "12px", flexWrap: "wrap" }}>
                <span style={{ fontSize: "10px", padding: "2px 8px", borderRadius: "4px", background: catColor.bg, color: catColor.color, border: `1px solid ${catColor.border}`, fontWeight: 500 }}>{p.category}</span>
                {(p.tags || []).slice(0, 2).map(t => <span key={t} style={{ fontSize: "10px", padding: "2px 6px", borderRadius: "4px", background: "var(--bg-body)", color: "var(--fg-3)", border: "1px solid var(--border)" }}>{t}</span>)}
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <span style={{ fontSize: "11px", color: "var(--fg-3)" }}>{p.author || "Lintasan"} · v{p.version || "1.0"}</span>
                {isInstalled ? (
                  <span style={{ fontSize: "12px", color: "var(--success)", fontWeight: 500 }}>✓ Installed</span>
                ) : (
                  <button onClick={() => install(p.id)} disabled={installing === p.id} style={{ ...btnPrimary, padding: "6px 12px", fontSize: "12px" }}>
                    {installing === p.id ? "..." : "Install"}
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </>
  );
}

/* ==================== AI GENERATE TAB ==================== */
function GenerateTab() {
  const [prompt, setPrompt] = useState("");
  const [name, setName] = useState("");
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState(null);
  const [installing, setInstalling] = useState(false);
  const [installed, setInstalled] = useState(false);
  const [error, setError] = useState("");

  const generate = async () => {
    if (!prompt.trim()) return;
    setGenerating(true); setResult(null); setError(""); setInstalled(false);
    try {
      const res = await fetch("/api/plugins/generate", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ prompt: prompt.trim(), name: name.trim() || undefined }) });
      const data = await res.json();
      if (data.ok) setResult(data);
      else setError(data.error || "Generation failed");
    } catch (e) { setError("Network error: " + e.message); }
    setGenerating(false);
  };

  const install = async () => {
    if (!result) return;
    setInstalling(true);
    const res = await fetch("/api/plugins", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ action: "create", name: result.name, code: result.code }) });
    const data = await res.json();
    if (data.ok) setInstalled(true);
    else setError(data.error || "Install failed");
    setInstalling(false);
  };

  return (
    <>
      {/* Input */}
      <div style={card}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "14px" }}>
          <div style={{ width: "32px", height: "32px", borderRadius: "8px", background: "linear-gradient(135deg, var(--primary), #8b5cf6)", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <span style={{ fontSize: "16px" }}>🤖</span>
          </div>
          <div>
            <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--fg-0)" }}>Describe your plugin</p>
            <p style={{ fontSize: "11px", color: "var(--fg-3)" }}>AI will generate working code from your description</p>
          </div>
        </div>

        <textarea value={prompt} onChange={e => setPrompt(e.target.value)} style={{ ...input, minHeight: "80px", marginBottom: "10px", resize: "vertical" }} placeholder="e.g. Block requests with more than 30 messages and return 400 error..." />

        <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
          <input value={name} onChange={e => setName(e.target.value)} style={{ ...input, width: "180px" }} placeholder="Plugin name (optional)" />
          <button onClick={generate} disabled={generating || !prompt.trim()} style={{ ...btnPrimary, background: "linear-gradient(135deg, var(--primary), #8b5cf6)", opacity: (!prompt.trim()) ? 0.5 : 1 }}>
            {generating ? "Generating..." : "✨ Generate"}
          </button>
        </div>
      </div>

      {/* Error */}
      {error && <div style={{ ...card, background: "var(--error-light)", borderColor: "rgba(239,68,68,0.3)" }}><p style={{ fontSize: "13px", color: "var(--error)" }}>⚠️ {error}</p></div>}

      {/* Result */}
      {result && (
        <div style={card} className="fade-in">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "12px" }}>
            <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--fg-0)" }}>{result.name}.js {result.model_used && <span style={{ fontSize: "11px", color: "var(--fg-3)", fontWeight: 400 }}>via {result.model_used}</span>}</p>
            <div style={{ display: "flex", gap: "8px" }}>
              {!installed ? (
                <button onClick={install} disabled={installing} style={{ ...btnPrimary, background: "var(--success)" }}>{installing ? "..." : "📦 Install"}</button>
              ) : (
                <span style={{ fontSize: "12px", color: "var(--success)", fontWeight: 600 }}>✓ Installed</span>
              )}
              <button onClick={() => navigator.clipboard.writeText(result.code)} style={btnSecondary}>📋 Copy</button>
            </div>
          </div>
          <pre style={{ background: "var(--bg-body)", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)", padding: "14px", fontSize: "11px", fontFamily: "var(--mono)", lineHeight: "1.6", color: "var(--fg-1)", overflow: "auto", maxHeight: "350px", whiteSpace: "pre-wrap" }}>{result.code}</pre>
          {installed && <p style={{ marginTop: "10px", fontSize: "12px", color: "var(--success)" }}>✓ Active now. Switch to "My Plugins" tab to manage.</p>}
        </div>
      )}

      {/* Examples */}
      {!result && !generating && (
        <div style={card}>
          <p style={{ fontSize: "12px", fontWeight: 600, color: "var(--fg-2)", marginBottom: "10px" }}>💡 Try these:</p>
          <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
            {["Block requests with more than 30 messages, return 400 error", "Add X-Request-ID UUID header to every response", "Log all requests to data/requests.jsonl with timestamp and model", "Block expensive models (gpt-4, claude-3-opus) outside 9am-6pm", "Auto-add system message 'be concise' if conversation > 5 messages", "Rate limit each API key to 10 req/min, return 429 if exceeded"].map((ex, i) => (
              <button key={i} onClick={() => setPrompt(ex)} style={{ textAlign: "left", padding: "8px 12px", background: "var(--bg-body)", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)", color: "var(--fg-2)", fontSize: "12px", cursor: "pointer" }}>{ex}</button>
            ))}
          </div>
        </div>
      )}
    </>
  );
}

/* ==================== HELPERS ==================== */
function generateTemplate(name) {
  return `export default {\n  name: "${name}",\n  version: "1.0.0",\n  description: "",\n  priority: 10,\n  enabled: true,\n  hooks: {\n    beforeRequest(ctx) {\n      // ctx: { model, messages, stream, auth, headers, metadata }\n    },\n    afterRequest(ctx, response) {\n      // response is parsed JSON\n    }\n  }\n};\n`;
}

function IconPlugin({ color = "currentColor" }) { return <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round"><path d="M12 2v4m0 12v4M4.93 4.93l2.83 2.83m8.48 8.48l2.83 2.83M2 12h4m12 0h4M4.93 19.07l2.83-2.83m8.48-8.48l2.83-2.83"/></svg>; }
function IconTrash() { return <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--error)" strokeWidth="2" strokeLinecap="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>; }
function IconCode() { return <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>; }

const card = { background: "var(--bg-card)", borderRadius: "var(--radius)", padding: "20px", boxShadow: "var(--shadow)", border: "1px solid var(--border)", marginBottom: "16px" };
const metricCell = { padding: "14px 20px", background: "var(--bg-card)" };
const metricLabel = { fontSize: "11px", color: "var(--fg-3)", marginBottom: "4px", textTransform: "uppercase", letterSpacing: "0.5px", fontWeight: 500 };
const metricValue = { fontSize: "20px", fontWeight: 700, color: "var(--fg-0)", fontFamily: "var(--mono)" };
const input = { width: "100%", padding: "9px 12px", background: "var(--bg-body)", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)", color: "var(--fg-0)", fontSize: "13px", outline: "none" };
const labelSt = { display: "block", fontSize: "12px", fontWeight: 500, color: "var(--fg-2)", marginBottom: "6px" };
const btnPrimary = { display: "inline-flex", alignItems: "center", gap: "6px", padding: "8px 14px", background: "var(--primary)", color: "#fff", border: "none", borderRadius: "var(--radius-sm)", fontSize: "12px", fontWeight: 500, cursor: "pointer" };
const btnSecondary = { display: "inline-flex", alignItems: "center", gap: "6px", padding: "8px 14px", background: "var(--bg-body)", color: "var(--fg-1)", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)", fontSize: "12px", fontWeight: 500, cursor: "pointer" };
const btnSmall = { display: "inline-flex", alignItems: "center", padding: "5px", background: "var(--primary-light)", border: "1px solid rgba(60,80,224,0.2)", borderRadius: "5px", cursor: "pointer" };
const tagBtn = { padding: "5px 10px", fontSize: "11px", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)", background: "var(--bg-body)", color: "var(--fg-3)", cursor: "pointer", fontWeight: 500, textTransform: "capitalize" };
const tagActive = { background: "var(--primary)", color: "#fff", borderColor: "var(--primary)" };
